In [3]:
import numpy as np

In [4]:
arr = np.ones(5)

In [5]:
arr = np.zeros(5)

In [6]:
arr

array([0., 0., 0., 0., 0.])

In [7]:
arr=np.arange(0,100,2)

In [8]:
arr = np.zeros(5)
arr + 10

array([10., 10., 10., 10., 10.])

In [9]:
arr

array([0., 0., 0., 0., 0.])

In [10]:
arr=np.arange(1,17)
arr=arr.reshape(4,4)

In [11]:
arr=np.eye(4)

In [49]:
np.random.rand()*5

3.8193799002200373

In [13]:
arr=np.random.randn(25)
arr=arr.reshape(5,5)

In [14]:
arr = np.linspace(1,5,20)

In [15]:
arr=np.arange(1,101)

In [16]:
arr=arr[40:]

In [17]:
arr=arr.reshape(6,10)

In [33]:
arr=np.arange(1,101)
arr=arr.reshape(10,10)
arr[6:,4:]
arr[:3,2:4]
arr=arr[:3,1].reshape(3,1)
arr=arr=np.arange(1,101).reshape(10,10)
arr[:,-1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [41]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [42]:
arr1

array([[2, 3, 4],
       [2, 3, 4],
       [3, 2, 0]])

In [43]:
arr2

array([[2, 1, 4],
       [4, 0, 3],
       [3, 1, 1]])

In [44]:
arr1+arr2

array([[4, 4, 8],
       [6, 3, 7],
       [6, 3, 1]])

In [45]:
arr1*arr2

array([[ 4,  3, 16],
       [ 8,  0, 12],
       [ 9,  2,  0]])

In [46]:
arr1.mean()

2.5555555555555554

In [50]:
arr1.sum()

23